<?php

namespace Vallas\ModelBundle\Repository;
use ESocial\ModelBundle\Entity\GenericRepository;

/**
 * AccionClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccionClienteRepository extends GenericRepository
{
}
