<?php

namespace Vallas\ModelBundle\Repository;

/**
 * BriefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BriefRepository extends \Doctrine\ORM\EntityRepository
{
}
