<?php

namespace Vallas\ModelBundle\Repository;

/**
 * CategoriaPropuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaPropuestaRepository extends \Doctrine\ORM\EntityRepository
{
}
