<?php

namespace Vallas\ModelBundle\Repository;

/**
 * CatorcenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatorcenaRepository extends \Doctrine\ORM\EntityRepository
{
}
