<?php

namespace Vallas\ModelBundle\Repository;
use ESocial\ModelBundle\Entity\GenericRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends GenericRepository
{
}
