<?php

namespace Vallas\ModelBundle\Repository;

/**
 * ComisionAgenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComisionAgenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
