<?php

namespace Vallas\ModelBundle\Repository;

/**
 * ComisionEjecutivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComisionEjecutivoRepository extends \Doctrine\ORM\EntityRepository
{
}
