<?php

namespace Vallas\ModelBundle\Repository;

/**
 * ContactoClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoClienteRepository extends \Doctrine\ORM\EntityRepository
{
}
