<?php

namespace Vallas\ModelBundle\Repository;

/**
 * MaterialImpresionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialImpresionRepository extends \Doctrine\ORM\EntityRepository
{
}
