<?php

namespace Vallas\ModelBundle\Repository;

/**
 * MedioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedioRepository extends \Doctrine\ORM\EntityRepository
{
}
