<?php

namespace Vallas\ModelBundle\Repository;

/**
 * MetaUbicacionFQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaUbicacionFQRepository extends \Doctrine\ORM\EntityRepository
{
}
