<?php

namespace Vallas\ModelBundle\Repository;

/**
 * MetaUbicacionFQCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaUbicacionFQCatRepository extends \Doctrine\ORM\EntityRepository
{
}
