<?php

namespace Vallas\ModelBundle\Repository;

/**
 * ParametrosPropuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametrosPropuestaRepository extends \Doctrine\ORM\EntityRepository
{
}
