<?php

namespace Vallas\ModelBundle\Repository;

/**
 * ParametroTpvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametroTpvRepository extends \Doctrine\ORM\EntityRepository
{
}
