<?php

namespace Vallas\ModelBundle\Repository;

/**
 * PlazaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlazaRepository extends \Doctrine\ORM\EntityRepository
{
}
