<?php

namespace Vallas\ModelBundle\Repository;

/**
 * PropuestaDetalleOutdoorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropuestaDetalleOutdoorRepository extends \Doctrine\ORM\EntityRepository
{
}
