<?php

namespace Vallas\ModelBundle\Repository;

/**
 * PropuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropuestaRepository extends \Doctrine\ORM\EntityRepository
{
}
