<?php

namespace Vallas\ModelBundle\Repository;

/**
 * PropuestaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropuestaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
