<?php

namespace Vallas\ModelBundle\Repository;

/**
 * ReportCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
