<?php

namespace Vallas\ModelBundle\Repository;
use ESocial\ModelBundle\Entity\GenericRepository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends GenericRepository
{
}
