<?php

namespace Vallas\ModelBundle\Repository;

/**
 * ReservaMedioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaMedioRepository extends \Doctrine\ORM\EntityRepository
{
}
