<?php

namespace Vallas\ModelBundle\Repository;

/**
 * RestriccionPropuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestriccionPropuestaRepository extends \Doctrine\ORM\EntityRepository
{
}
