<?php

namespace Vallas\ModelBundle\Repository;

/**
 * RestriccionUbicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestriccionUbicacionRepository extends \Doctrine\ORM\EntityRepository
{
}
