<?php

namespace Vallas\ModelBundle\Repository;

/**
 * RestriccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestriccionRepository extends \Doctrine\ORM\EntityRepository
{
}
