<?php

namespace Vallas\ModelBundle\Repository;

/**
 * SubtipoMedioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubtipoMedioRepository extends \Doctrine\ORM\EntityRepository
{
}
