<?php

namespace Vallas\ModelBundle\Repository;

/**
 * SubtipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubtipoRepository extends \Doctrine\ORM\EntityRepository
{
}
