<?php

namespace Vallas\ModelBundle\Repository;

/**
 * TipoAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAccionRepository extends \Doctrine\ORM\EntityRepository
{
}
