<?php

namespace Vallas\ModelBundle\Repository;

/**
 * TipoMedioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMedioRepository extends \Doctrine\ORM\EntityRepository
{
}
