<?php

namespace Vallas\ModelBundle\Repository;
use ESocial\ModelBundle\Entity\UserRepository as ESocialUserRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends ESocialUserRepository
{
    public function getQueryBuilder(){
        $qb = parent::getQueryBuilder();
        $qb->leftJoin('u.user_paises', 'user_paises');
        return $qb;
    }
}
