<?php

namespace Vallas\ModelBundle\Repository;
use ESocial\ModelBundle\Entity\UserRepository as ESocialUserRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends ESocialUserRepository
{
}
