<?php

namespace Vallas\ModelBundle\Repository;

/**
 * UserPaisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPaisRepository extends \Doctrine\ORM\EntityRepository
{
}
