<?php

namespace Vallas\ModelBundle\Repository;

/**
 * ZonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZonaRepository extends \Doctrine\ORM\EntityRepository
{
}
